#!/bin/sh
APPDIR=`dirname $0`;

java -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$CLASSPATH" com.google.gwt.dev.GWTCompiler -style PRETTY -out "$APPDIR/www" "$@" org.barberaware.GASdotto;
# java -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:$CLASSPATH" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.barberaware.GASdotto;

chmod -R a+rwx www
