#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/home/madbob/sorgenti_vari/gwt-linux-1.5.2/gwt-user.jar:/home/madbob/sorgenti_vari/gwt-linux-1.5.2/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.barberaware.GASdotto/GASdotto.html;
